# Generated by Django 4.2.7 on 2023-12-01 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsfeedbacks',
            name='img',
            field=models.ImageField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='header',
            name='img',
            field=models.ImageField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='provideservices',
            name='svg',
            field=models.ImageField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='tools',
            name='svg',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
