# Generated by Django 4.2.7 on 2023-11-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('paragraph', models.TextField(max_length=200)),
                ('img', models.ImageField(upload_to='uploads')),
            ],
        ),
        migrations.DeleteModel(
            name='MainImage',
        ),
        migrations.DeleteModel(
            name='MainTitle',
        ),
        migrations.DeleteModel(
            name='MainTitleParagraph',
        ),
    ]
