# Generated by Django 4.2.7 on 2023-12-02 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stats',
            old_name='YearsExperience',
            new_name='happyClients',
        ),
        migrations.AddField(
            model_name='stats',
            name='yearsExperience',
            field=models.IntegerField(default=0),
        ),
    ]
