# Generated by Django 4.2.7 on 2023-12-01 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_clientsfeedbacks_img_alter_header_img_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreelanceClients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='uploads/')),
            ],
        ),
    ]
