# Generated by Django 4.2.7 on 2023-12-01 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_freelanceclients'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelanceclients',
            name='name',
            field=models.TextField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='education',
            name='link',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='end_date',
            field=models.TextField(default='present', max_length=50),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='link',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
