# Generated by Django 4.2.7 on 2023-12-01 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_education_end_date_alter_education_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelanceclients',
            name='name',
        ),
    ]
